functions,
js-tasks-ru/jsbasic-20240115_petrmazarovich pull request #5
Opened 2024-02-04 16:14 UTC by PMazarovich

2024-02-04 16:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-05 14:07 UTC, SinimaWath requested changes

2024-02-05 14:07 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  Array.from(table.querySelectorAll("td")).filter((node) => checkEquality(node.innerText) ? node.style.backgroundColor = "red" : {});
`filter ` - фильтр тут не нужен, так как нет условия, так что здесь: `forEach` подходит

2024-02-05 14:07 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  Array.from(table.querySelectorAll("tr")).map((trNode) => Array.from(trNode.children).map(tdNode => modifyElement(trNode, tdNode)));
Тут большого смысла в map нет, так как не используется результат вызова функции, поэтому лучше `forEach`

2024-02-05 14:07 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return arr.filter((x) => {return x >= a && x <= b;});
```suggestion
  return arr.filter((x) => x >= a && x <= b);
```

2024-02-05 14:07 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  });
```suggestion
  return users.map((user) => user.name);
```

2024-02-05 15:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2024-02-09 12:35 UTC, SinimaWath approved these changes
Все круто!

2024-02-09 12:36 UTC, merged